name: 上傳Python包

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Build release distributions
        run: |
          # NOTE: put your own distribution build steps here.
          pip install poetry
          poetry build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      # IMPORTANT: 對於可信任發布來說，此權限是必要的
      id-token: write

    steps:
      - name: 檢索發布發行版
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: 將發行版發佈到 PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
